name: Update languages

on:
  push:
    branches:
      - main
    paths:
      - "langs/**"

jobs:
  update-langs:
    name: Update all languages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get langs diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            langs/*.json
      - name: Install dependencies
        run: yarn
      - name: Build scripts
        run: yarn build
      - name: Run script
        run: yarn update-langs ${{ env.GIT_DIFF_FILTERED }}
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
